apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: yshop
type: Opaque
data:
  # Base64 encoded: yixiang-drink
  mysql-database: eWl4aWFuZy1kcmluaw==
  # Base64 encoded: 123456
  mysql-root-password: MTIzNDU2
